#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
build_dir="${script_dir}/build"
layout_config_file="${script_dir}/nips_layout_config.tex"
left_padding_delta="0pt"
right_padding_delta="0pt"
force_rebuild=false

usage() {
  cat <<EOF
Usage: bash docs/NIPS_2026_tsENV/build.sh [--left-padding <delta>] [--right-padding <delta>] [--force]

Build the NeurIPS-style tsENV manuscript PDF.

Options:
  --left-padding <delta>   Relative adjustment from the default left margin.
  --right-padding <delta>  Relative adjustment from the default right margin.
  --force                  Delete target artifacts and force a clean rebuild.
  --help                   Show this help message.

Examples:
  bash docs/NIPS_2026_tsENV/build.sh
  bash docs/NIPS_2026_tsENV/build.sh --left-padding -25mm --right-padding +25mm
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --left-padding)
      if [ "$#" -lt 2 ] || [[ "$2" == --* ]]; then
        echo "Error: --left-padding requires a value." >&2
        usage >&2
        exit 1
      fi
      left_padding_delta="$2"
      shift 2
      ;;
    --right-padding)
      if [ "$#" -lt 2 ] || [[ "$2" == --* ]]; then
        echo "Error: --right-padding requires a value." >&2
        usage >&2
        exit 1
      fi
      right_padding_delta="$2"
      shift 2
      ;;
    --force)
      force_rebuild=true
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown argument '$1'." >&2
      usage >&2
      exit 1
      ;;
  esac
done

if ! command -v pdflatex >/dev/null 2>&1; then
  echo "Error: pdflatex command not found." >&2
  exit 1
fi

if ! command -v bibtex >/dev/null 2>&1; then
  echo "Error: bibtex command not found." >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "Error: python3 command not found." >&2
  exit 1
fi

mkdir -p "$build_dir"

cd "$script_dir"

cleanup_legacy_build_artifacts() {
  rm -f "${build_dir}"/*_build_wrapper.*
}

cleanup_standalone_appendix_outputs() {
  rm -f \
    "${script_dir}/appendix_environment.pdf" \
    "${script_dir}/appendix_agents.pdf" \
    "${build_dir}/appendix_environment.pdf" \
    "${build_dir}/appendix_agents.pdf"
}

write_layout_config() {
  python3 - <<'PY' "${layout_config_file}" "${left_padding_delta}" "${right_padding_delta}"
from pathlib import Path
import sys

target = Path(sys.argv[1])
left = sys.argv[2]
right = sys.argv[3]
text = (
    "% Generated by docs/NIPS_2026_tsENV/build.sh.\n"
    f"\\providecommand{{\\manualDocLeftPaddingDelta}}{{{left}}}\n"
    f"\\providecommand{{\\manualDocRightPaddingDelta}}{{{right}}}\n"
)
if not target.exists() or target.read_text() != text:
    target.write_text(text)
PY
}

run_pdflatex() {
  local tex_name="$1"

  (
    cd "${script_dir}"
    pdflatex -interaction=nonstopmode -halt-on-error -file-line-error \
      -output-directory=build "${tex_name}"
  )
}

run_pdflatex_with_optional_sigsegv_recovery() {
  local tex_name="$1"
  local allow_sigsegv="$2"
  local rc=0

  set +e
  (
    cd "${script_dir}"
    pdflatex -interaction=nonstopmode -halt-on-error -file-line-error \
      -output-directory=build "${tex_name}"
  )
  rc=$?
  set -e

  if [ "${rc}" -eq 0 ]; then
    return 0
  fi

  if [ "${allow_sigsegv}" = "true" ] && [ "${rc}" -eq 139 ]; then
    echo "Warning: pdflatex hit the known padded-manuscript intermediate-pass segfault; continuing with recovery pass." >&2
    return 0
  fi

  return "${rc}"
}

run_bibtex() {
  local job_stem="$1"

  (
    cd "${build_dir}"
    BIBINPUTS="${script_dir}:${build_dir}:" BSTINPUTS="${script_dir}:" bibtex "${job_stem}"
  )
}

clean_target_artifacts() {
  local job_stem="$1"

  rm -f \
    "${script_dir}/${job_stem}.out" \
    "${script_dir}/${job_stem}.aux" \
    "${build_dir}/${job_stem}.aux" \
    "${build_dir}/${job_stem}.bbl" \
    "${build_dir}/${job_stem}.blg" \
    "${build_dir}/${job_stem}.fdb_latexmk" \
    "${build_dir}/${job_stem}.fls" \
    "${build_dir}/${job_stem}.log" \
    "${build_dir}/${job_stem}.out" \
    "${build_dir}/${job_stem}.pdf" \
    "${build_dir}/${job_stem}.synctex.gz"
}

reset_unstable_outline_state() {
  local job_stem="$1"

  rm -f "${script_dir}/${job_stem}.out" "${build_dir}/${job_stem}.out"
}

needs_padded_main_recovery() {
  local job_stem="$1"

  if [ "${job_stem}" != "main" ]; then
    return 1
  fi

  if [ "${left_padding_delta}" = "0pt" ] && [ "${right_padding_delta}" = "0pt" ]; then
    return 1
  fi

  return 0
}

compile_tex() {
  local tex_name="$1"
  local with_bib="${2:-false}"
  local job_stem="${tex_name%.tex}"
  local output_pdf="${script_dir}/${job_stem}.pdf"

  clean_target_artifacts "${job_stem}"
  run_pdflatex "${tex_name}"
  if [ "${with_bib}" = "true" ]; then
    run_bibtex "${job_stem}"
  fi
  reset_unstable_outline_state "${job_stem}"
  if needs_padded_main_recovery "${job_stem}"; then
    run_pdflatex_with_optional_sigsegv_recovery "${tex_name}" "true"
  else
    run_pdflatex "${tex_name}"
  fi
  if [ "${with_bib}" = "true" ]; then
    run_pdflatex "${tex_name}"
  fi

  if [ ! -f "${build_dir}/${job_stem}.pdf" ]; then
    echo "Error: expected rendered PDF at ${build_dir}/${job_stem}.pdf" >&2
    exit 1
  fi

  cp "${build_dir}/${job_stem}.pdf" "${output_pdf}"
  printf 'Built %s\n' "${output_pdf}"
}

main_inputs_newer_than_pdf() {
  local output_pdf="${script_dir}/main.pdf"

  if [ ! -f "${output_pdf}" ]; then
    return 0
  fi

  if [ ! -f "${build_dir}/main.aux" ]; then
    return 0
  fi

  if find "${script_dir}" \
    \( -path "${build_dir}" -o -path "${build_dir}/*" \) -prune -o \
    -type f \
    \( -name '*.tex' -o -name '*.sty' -o -name '*.bib' -o -name '*.pdf' \) \
    ! -name 'main.pdf' \
    ! -name '*.aux' \
    ! -name '*.out' \
    ! -name '*.log' \
    ! -name '*.bbl' \
    ! -name '*.blg' \
    -newer "${output_pdf}" \
    -print -quit | grep -q .; then
    return 0
  fi

  if [ "${layout_config_file}" -nt "${output_pdf}" ]; then
    return 0
  fi

  return 1
}

cleanup_legacy_build_artifacts
cleanup_standalone_appendix_outputs
write_layout_config

if [ "${force_rebuild}" = "true" ] || main_inputs_newer_than_pdf; then
  compile_tex main.tex true
else
  printf 'NIPS manuscript is up to date: %s\n' "${script_dir}/main.pdf"
fi
